export const START_FETCH_FILM = 'START_FETCH_FILM';
export const FETCH_FILM = 'FETCH_FILM';
export const FETCH_FILM_REJECT = 'FETCH_FILM_REJECT';
export const FETCH_FILM_SUCCESS = 'FETCH_FILM_SUCCESS';
