export const START_FETCH_SEARCH = 'START_FETCH_SEARCH';
export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_REJECT = 'FETCH_SEARCH_REJECT';
export const CHANGE_SEARCH_FILTER = 'CHANGE_SEARCH_FILTER';
export const CHOOSE_FILM = 'CHOOSE_FILM';
